// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130203200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entitys.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("beginning");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_events_genre_id");

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BasePrice = 50m,
                            Beginning = new DateTime(2025, 12, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            Name = "Rock Concert",
                            Venue = "Stadium A"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePrice = 50m,
                            Beginning = new DateTime(2025, 12, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            Name = "Rock Concert",
                            Venue = "Stadium A"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePrice = 40m,
                            Beginning = new DateTime(2025, 12, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 3,
                            Name = "Jazz Night",
                            Venue = "Club C"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePrice = 50m,
                            Beginning = new DateTime(2025, 12, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 2,
                            Name = "Pop Festival",
                            Venue = "Arena B"
                        });
                });

            modelBuilder.Entity("Entitys.EventRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_event_ratings");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_ratings_event_id");

                    b.ToTable("event_ratings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            EventId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("Entitys.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jazz"
                        });
                });

            modelBuilder.Entity("Entitys.Event", b =>
                {
                    b.HasOne("Entitys.Genre", "Genre")
                        .WithMany("Events")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_genres_genre_id");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Entitys.EventRating", b =>
                {
                    b.HasOne("Entitys.Event", "Event")
                        .WithMany("Ratings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_ratings_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Entitys.Event", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Entitys.Genre", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
